### ISSUE TITLE
[Idea] Add a method to check if the routes overlap

### ISSUE THREAD

**Issue by aochagavia** [conduit-rust/route-recognizer.rs#15]
This would be pretty nice, specially considering a future macro that can catch overlap at compile time (as suggested in https://github.com/iron/router/issues/48#issuecomment-61427630). How difficult would it be to implement this?

**Comment by Parakleta** [comment]
I think overlap detection would be quite difficult.  You'd need to do some transitive closure on the NFA to find out if any input sequences could map to multiple accept states.

Overlaps aren't necessarily a problem however, since you may have both explicit and wildcard paths that overlap.  There is currently an ordering algorithm for disambiguating overlaps which works for trivial cases.

**Comment by aochagavia** [comment]
I think you are right... Closing this.
